module.exports = Object.freeze({
  PLAYER_RADIUS: 28,
  PLAYER_MAX_HP: 100,
  PLAYER_SPEED: 210,
  BULLET_SPEED: 510,
  PLAYER_FIRE_COOLDOWN: 0.4,
  BULLET_DAMAGE: 13,
  SCORE_PER_SECOND: 2,
  SCORE_BULLET_HIT: 15,
  BULLET_RADIUS: 5,
  PLAYER_HEALTH_REGEN: 2.5,
  PLAYER_DAMAGE: 2,

  MAP_SIZE: 2700,
  MSG_TYPES: {
    JOIN_GAME: 'join_game',
    GAME_UPDATE: 'update',
    INPUT: 'input',
    GAME_OVER: 'dead'
  }
});
