module.exports = Object.freeze({
  PLAYER_RADIUS: 15,
  PLAYER_MAX_HP: 150,
  PLAYER_SPEED: 180,
  PLAYER_BOOST_SPEED: 500,
  BULLET_SPEED: 450,
  PLAYER_FIRE_COOLDOWN: 0.65,
  BULLET_DAMAGE: 6,
  SCORE_PER_SECOND: 0.5,
  SCORE_BULLET_HIT: 10,
  BULLET_RADIUS: 5,
  PLAYER_HEALTH_REGEN: 7,
  PLAYER_DAMAGE: 0.75,
  MINIMAP_SIZE_PERCENTAGE: 0.2,
  PLAYER_ACCELERATION: 200,
  PLAYER_SCORE_DROP_BOOSTING: 6,
  SERVER_FOOD_START: 1,
  AVG_FOOD_SIZE: 3,
  AVG_FOOD_SCORE: 1,
  FOOD_SPAWN_RATE: 1,
  MAX_SERVER_FOOD: 10,

  MAP_SIZE: 2000,
  MSG_TYPES: {
    JOIN_GAME: 'join_game',
    GAME_UPDATE: 'update',
    INPUT: 'input',
    GAME_OVER: 'dead',
    KEY_PRESS: 'keyDown',
    KEY_RELEASE: 'keyUp'
  }
});
